// Code generated by soagen; DO NOT EDIT.
package veteran

import (
	"slices"
)

type VeteranSlice struct {
	LocalVeteranId       []int
	CardId               []int
	CreateTime           []string
	RankScore            []int
	FactorIdArray        [][]int
	Speed                []int
	Stamina              []int
	Power                []int
	Guts                 []int
	Wit                  []int
	SuccessionCharaArray [][]SuccessionChara
	WinSaddleIdArray     [][]int
	NicknameIdArray      [][]int
}

func (s VeteranSlice) Get(i int) Veteran {
	var t Veteran
	t.LocalVeteranId = s.LocalVeteranId[i]
	t.CardId = s.CardId[i]
	t.CreateTime = s.CreateTime[i]
	t.RankScore = s.RankScore[i]
	t.FactorIdArray = s.FactorIdArray[i]
	t.Speed = s.Speed[i]
	t.Stamina = s.Stamina[i]
	t.Power = s.Power[i]
	t.Guts = s.Guts[i]
	t.Wit = s.Wit[i]
	t.SuccessionCharaArray = s.SuccessionCharaArray[i]
	t.WinSaddleIdArray = s.WinSaddleIdArray[i]
	t.NicknameIdArray = s.NicknameIdArray[i]
	return t
}

func (s VeteranSlice) Set(i int, t Veteran) {
	s.LocalVeteranId[i] = t.LocalVeteranId
	s.CardId[i] = t.CardId
	s.CreateTime[i] = t.CreateTime
	s.RankScore[i] = t.RankScore
	s.FactorIdArray[i] = t.FactorIdArray
	s.Speed[i] = t.Speed
	s.Stamina[i] = t.Stamina
	s.Power[i] = t.Power
	s.Guts[i] = t.Guts
	s.Wit[i] = t.Wit
	s.SuccessionCharaArray[i] = t.SuccessionCharaArray
	s.WinSaddleIdArray[i] = t.WinSaddleIdArray
	s.NicknameIdArray[i] = t.NicknameIdArray
}

func (s VeteranSlice) Len() int {
	return min(
		len(s.LocalVeteranId),
		len(s.CardId),
		len(s.CreateTime),
		len(s.RankScore),
		len(s.FactorIdArray),
		len(s.Speed),
		len(s.Stamina),
		len(s.Power),
		len(s.Guts),
		len(s.Wit),
		len(s.SuccessionCharaArray),
		len(s.WinSaddleIdArray),
		len(s.NicknameIdArray),
	)
}

func (s VeteranSlice) Cap() int {
	return min(
		cap(s.LocalVeteranId),
		cap(s.CardId),
		cap(s.CreateTime),
		cap(s.RankScore),
		cap(s.FactorIdArray),
		cap(s.Speed),
		cap(s.Stamina),
		cap(s.Power),
		cap(s.Guts),
		cap(s.Wit),
		cap(s.SuccessionCharaArray),
		cap(s.WinSaddleIdArray),
		cap(s.NicknameIdArray),
	)
}

func (s VeteranSlice) Slice(low, high, max int) VeteranSlice {
	return VeteranSlice{
		LocalVeteranId:       s.LocalVeteranId[low:high:max],
		CardId:               s.CardId[low:high:max],
		CreateTime:           s.CreateTime[low:high:max],
		RankScore:            s.RankScore[low:high:max],
		FactorIdArray:        s.FactorIdArray[low:high:max],
		Speed:                s.Speed[low:high:max],
		Stamina:              s.Stamina[low:high:max],
		Power:                s.Power[low:high:max],
		Guts:                 s.Guts[low:high:max],
		Wit:                  s.Wit[low:high:max],
		SuccessionCharaArray: s.SuccessionCharaArray[low:high:max],
		WinSaddleIdArray:     s.WinSaddleIdArray[low:high:max],
		NicknameIdArray:      s.NicknameIdArray[low:high:max],
	}
}

func (s VeteranSlice) Grow(n int) VeteranSlice {
	return VeteranSlice{
		LocalVeteranId:       slices.Grow(s.LocalVeteranId, n),
		CardId:               slices.Grow(s.CardId, n),
		CreateTime:           slices.Grow(s.CreateTime, n),
		RankScore:            slices.Grow(s.RankScore, n),
		FactorIdArray:        slices.Grow(s.FactorIdArray, n),
		Speed:                slices.Grow(s.Speed, n),
		Stamina:              slices.Grow(s.Stamina, n),
		Power:                slices.Grow(s.Power, n),
		Guts:                 slices.Grow(s.Guts, n),
		Wit:                  slices.Grow(s.Wit, n),
		SuccessionCharaArray: slices.Grow(s.SuccessionCharaArray, n),
		WinSaddleIdArray:     slices.Grow(s.WinSaddleIdArray, n),
		NicknameIdArray:      slices.Grow(s.NicknameIdArray, n),
	}
}

type SuccessionCharaSlice struct {
	FactorIdArray    [][]int
	WinSaddleIdArray [][]int
	PositionId       []int
}

func (s SuccessionCharaSlice) Get(i int) SuccessionChara {
	var t SuccessionChara
	t.FactorIdArray = s.FactorIdArray[i]
	t.WinSaddleIdArray = s.WinSaddleIdArray[i]
	t.PositionId = s.PositionId[i]
	return t
}

func (s SuccessionCharaSlice) Set(i int, t SuccessionChara) {
	s.FactorIdArray[i] = t.FactorIdArray
	s.WinSaddleIdArray[i] = t.WinSaddleIdArray
	s.PositionId[i] = t.PositionId
}

func (s SuccessionCharaSlice) Len() int {
	return min(
		len(s.FactorIdArray),
		len(s.WinSaddleIdArray),
		len(s.PositionId),
	)
}

func (s SuccessionCharaSlice) Cap() int {
	return min(
		cap(s.FactorIdArray),
		cap(s.WinSaddleIdArray),
		cap(s.PositionId),
	)
}

func (s SuccessionCharaSlice) Slice(low, high, max int) SuccessionCharaSlice {
	return SuccessionCharaSlice{
		FactorIdArray:    s.FactorIdArray[low:high:max],
		WinSaddleIdArray: s.WinSaddleIdArray[low:high:max],
		PositionId:       s.PositionId[low:high:max],
	}
}

func (s SuccessionCharaSlice) Grow(n int) SuccessionCharaSlice {
	return SuccessionCharaSlice{
		FactorIdArray:    slices.Grow(s.FactorIdArray, n),
		WinSaddleIdArray: slices.Grow(s.WinSaddleIdArray, n),
		PositionId:       slices.Grow(s.PositionId, n),
	}
}
